name: connectivity_monitor
description: "A Flutter package to monitor internet connectivity with dynamic UI updates and toast notifications."
version: 1.0.8
homepage: "https://github.com/MahmoudNabil14/connectivity_monitor"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.4
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
